#!/bin/bash
. ./aws-setup || exit 1

aws ec2 describe-instances > /tmp/instances || exit 1

num=$(jq '.Reservations[].Instances | length' /tmp/instances)

if [[ $num != '' ]]; then
    printf '%s\n' "There's already an instance running. bailing out."
    printf "to terminate instance, run:\n"
    printf "aws ec2 terminate-instances --instance-id %s\n" $(jq '.Reservations[].Instances[].InstanceId' /tmp/instances)
    exit 1
fi

cmd=(aws ec2 run-instances \
	 --image-id "ami-0f918f7e67a3323f0" \
	 --subnet-id "subnet-02e7f17ee115e10c6" \
	 --instance-type "t2.micro" \
	 --user-data file://cloud-init.sh )

printf '%s\n' "${cmd[*]}"
read -p "run?(y/n)" ans
if [[ $ans == 'y' ]]; then
    "${cmd[@]}"
fi
