#!/bin/bash
ask(){
	read -p "$@" x
	printf '%s\n' "$x"
}

if [[ -z $AWS_ACCESS_KEY_ID ]]; then
	export AWS_ACCESS_KEY_ID=$(ask "AWS_ACCESS_KEY_ID: ")
fi
if [[ -z $AWS_SECRET_ACCESS_KEY ]]; then
	export AWS_SECRET_ACCESS_KEY=$(ask "AWS_SECRET_ACCESS_KEY: ")
fi

if [[ -z $AWS_DEFAULT_REGION ]]; then
	export AWS_DEFAULT_REGION="ap-south-1"
fi


