#!/bin/bash
usage(){
    cat >&2
    exit 1
}<<EOF
upload-logs bucket-name logs...

upload the given files to the s3 bucket's log/ directory.
EOF

. ../week-3/aws-setup

if (( $# < 2 )); then
    usage
fi

bucket=$1
shift

if [[ $bucket = s3://* ]]; then
    bucket=${bucket#s3://}
fi

aws s3 cp "$@" "s3://$bucket"
