#!/bin/bash
usage(){
	cat >&2
	exit 1
} <<EOF
new-user username [publick-key [useradd-options] ]

creates a new user, giving it sudo perimssions.
the public key is appended to ~/.ssh/authorized_keys
any options provided are passed to useradd as-is.
EOF

die(){
	printf '%s\n' "$*" >&2
	exit 1
}

group=sudo
key=$2
uname=$1
shift 2

if [[ -z $uname ]] || [[ $uname = -h ]]; then
	usage
fi

[[ $EUID = 0 ]] || die "must be root"

if [[ $(uname -r) = *amzn* ]]; then
	# amazon linux, set group sudo for sudo permission
	if ! grep -rm1 '%sudo' /etc/sudoers{,.d} ; then
		out=/etc/sudoers.d/$group.conf
		printf '%%%s ALL=(ALL:ALL) ALL\n' "$group" >> "$out" || die "couldn't add group $group to $out"
	fi
fi

useradd -m -G "$group" "$@" "$uname" || die "useradd failed"
passwd=$(LC_ALL=C grep -ao '[[:alnum:]]' /dev/random | paste -sd '' | head -c 8)
printf '%s\n' "$passwd" "$passwd" | passwd "$uname"
printf '%s\n' "password: $passwd"

if [[ -n $key ]]; then

su "$uname" <<EOF
mkdir -p ~/.ssh/
chmod 700 ~/.ssh
printf '%s\n' "$key" >> ~/.ssh/authorized_keys
EOF

fi
